<?php

/**
 * @file
 * Empty module file (migration code contained in includes).
 */

define('SURGERY_MIGRATION_GROUP', 'surgery');

/**
 * Implements hook_hook_info().
 */
function surgery_migration_hook_info() {
  $info['surgery_migration_overrides'] = array('group' => 'migrate');
  return $info;
}

/**
 * Implements hook_form_alter() for migrate_migration_info().
 */
function surgery_migration_form_migrate_migration_info_alter(&$form, &$form_state) {
  // Display the actual class used for the migration.
  $migration_name = $form_state['build_info']['args'][1];
  $migration = Migration::getInstance($migration_name);
  $form['overview']['class_name'] = array(
    '#type' => 'item',
    '#title' => t('Migration class name:'),
    '#markup' => get_class($migration),
  );
  $form['overview']['description']['#access'] = !empty($form['overview']['description']['#markup']);
}
